# Generated by Django 3.0.5 on 2020-05-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('adres', models.CharField(max_length=200)),
                ('bank', models.TextField(max_length=500)),
                ('unp', models.CharField(max_length=7)),
                ('kontact', models.CharField(max_length=50)),
                ('preabon', models.CharField(max_length=50)),
                ('pasport', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('tarif', models.CharField(max_length=20)),
                ('schet', models.CharField(max_length=50)),
                ('money', models.CharField(max_length=3)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workplace.Abonent')),
            ],
        ),
    ]
